name: Auto Refresh Zoho Data

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  refresh:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas

      - name: Run Zoho Refresh Script
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
          ORG_ID: ${{ secrets.ORG_ID }}
        run: |
          python import_requests.py   # غيّر هذا إذا اسم ملفك مختلف

      - name: List files (for debug)
        run: ls -la

      - name: Commit and Push Updated JSON
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          if [ -f "profit_loss.json" ]; then
            echo "Found profit_loss.json — checking for changes..."
            git add profit_loss.json
            if ! git diff --cached --quiet; then
              git commit -m "Auto update profit_loss.json"
              git push
              echo "✅ profit_loss.json committed and pushed."
            else
              echo "ℹ️ No changes to commit."
            fi
          else
            echo "⚠️ profit_loss.json not found — skipping commit step."
          fi
