name: Run Zoho Refresh Script

on:
  schedule:
    - cron: "0 * * * *"  # كل ساعة (بتوقيت UTC)
  workflow_dispatch:     # لتشغيله يدويًا من GitHub
  
jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests

      - name: Run Python script
        run: python import_requests.py
